//
//  MessageModels.swift
//  Arattai-IOS
//
//  Created by zs-mac-4 on 01/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
struct ChatMessage {
    let text: String
    let isIncoming: Bool
    let date: Date
}

